### ISSUE TITLE
PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by kunlunxu1** [fan-ziqi/rl_sar#12]
我使用iscaacsim训练的文件中没有constants.pkl
![2024-08-14 12-27-11 的屏幕截图](https://github.com/user-attachments/assets/46957065-217c-4356-86db-7cf191dc6e4a)
![2024-08-14 12-28-35 的屏幕截图](https://github.com/user-attachments/assets/fab39a52-4a46-40c7-bc24-7529b8171c16)
请问大佬的policy是怎么训练的

**Comment by fan-ziqi** [comment]
本项目不需要constants.pkl，训练过程参考https://github.com/fan-ziqi/robot_lab

**Comment by fan-ziqi** [comment]
你有没有导出为jit？
https://github.com/fan-ziqi/robot_lab/blob/14d8b9d18354bccd9dfccb198f8d11ea9303887d/scripts/rsl_rl/play.py#L124-L129

**Comment by kunlunxu1** [comment]
> 你有没有导出为jit？
> 
> https://github.com/fan-ziqi/robot_lab/blob/14d8b9d18354bccd9dfccb198f8d11ea9303887d/scripts/rsl_rl/play.py#L124-L129
> 
> ```python
>     export_policy_as_jit(
>         actor_critic=ppo_runner.alg.actor_critic,
>         normalizer=ppo_runner.obs_normalizer,
>         path=export_model_dir,
>         filename="policy.pt",
>     )
> ```

是没有导出为jit，我去试一下，谢谢大佬

**Comment by popocheng** [comment]
大佬们问题解决了吗，我这边有导出为jit，还是报这个错误
