### ISSUE TITLE
[New Robot] OpenLoong Support

### ISSUE THREAD

**Issue by kunlunxu1** [fan-ziqi/rl_sar#13]
大佬，再请问一下，我尝试用在isaacsim中训练好的青龙去sim2sim，但是在gazebo中一直瘫着，该怎么去改进

**Comment by fan-ziqi** [comment]
您可以把代码传到 [devel-openloong](https://github.com/fan-ziqi/rl_sar/tree/devel-openloong) 分支，开一个PR即可，我有空帮你看看。
