### ISSUE TITLE
Something is wrong with the compilation process.

### ISSUE THREAD

**Issue by QBH267** [fan-ziqi/rl_sar#17]
I went to install the ros environment in docker, then installed the required dependencies in order, and finally ran the catkin build command and got the following error.
By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "catkin", but CMake did not find one.
Could not find a package configuration file provided by “catkin“ : catkinConfig.cmake.

**Comment by fan-ziqi** [comment]
Please provide the complete error message.

**Comment by fan-ziqi** [comment]
Long time no reply, close this issue.
