### ISSUE TITLE
Simplified readme dependency installation

### ISSUE THREAD

**Issue by legubiao** [fan-ziqi/rl_sar#24]
Hello Fan,

Thank you for your great work.

I noticed that in the README file, you used `git clone` and `make install` to install the `yaml-cpp` and `lcm` libraries. As I tested, both of them can be installed using the apt command:

```bash
sudo apt-get install liblcm-dev libyaml-cpp-dev
```

I think this process will be easier for beginners. As I tested on my Ubuntu 20.04, I didn’t encounter any problems; both the Gazebo simulation and control program worked smoothly.

Does this look good to you?

**Comment by fan-ziqi** [comment]
Thank you for your contribution! I'll modify README after testing

**Comment by fan-ziqi** [comment]
The installation in README has been updated!
