### ISSUE TITLE
Bug in rl_sar During Real-world Deployment: Controller Crashes on Rotation Over 180 Degrees

### ISSUE THREAD

**Issue by zma69650** [fan-ziqi/rl_sar#26]
When using the go2 functionality in real-world deployment, the controller crashes whenever the rotation exceeds 180 degrees.

**Comment by fan-ziqi** [comment]
You can check if there is a jump in the quaternion at 180 degrees, preferably by providing screenshots or data
Also, is it convenient for you to contribute your go2 deployment code?
---- Replied Message ----
From JiJie ***@***.***> Date 10/11/2024 10:37 To ***@***.***> Cc ***@***.***> Subject [fan-ziqi/rl_sar] Bug in rl_sar During Real-world Deployment: Controller Crashes on Rotation Over 180 Degrees (Issue #26) 
When using the go2 functionality in real-world deployment, the controller crashes whenever the rotation exceeds 180 degrees.

**Comment by zma69650** [comment]
rl_sar has been very helpful to me, thank you for your response!
I had the robot rotate counterclockwise through four orientations, then compared the quaternions between the simulation and the real-world deployment.
sim 1:
![2024-10-11_11-04](https://github.com/user-attachments/assets/a11198b7-8fa1-46a4-96c8-7c19198de783)
sim 2:
![2024-10-11_11-05](https://github.com/user-attachments/assets/6ef87e9a-08c9-4364-a2bc-134cff60f730)
real 2:
![real_222](https://github.com/user-attachments/assets/7514ec29-644d-4908-8f4a-2c2dbff79e73)
sim 3:
![2024-10-11_11-05_1](https://github.com/user-attachments/assets/a597a53d-1f7e-4b3e-860c-b34a61f83e86)
real 3:
![real_333](https://github.com/user-attachments/assets/c2321255-f681-4153-8e85-ea066852a9c7)
sim 4: 
![2024-10-11_11-06](https://github.com/user-attachments/assets/a5a74a49-ef84-4dc8-acb0-ac4baff0b110)
real 4:
![real_555](https://github.com/user-attachments/assets/67efc5b4-e0d5-4560-91d1-fdd35c914d38)
Could it be that the quaternion in the real-world deployment reached 1, causing the error? 
This could be a numerical issue in the code. Initially, the values were normal, but when I had go2 stand, the quaternion values only had two decimal places.

**Comment by zma69650** [comment]
The quaternion received when it's functioning normally is:
![real_1](https://github.com/user-attachments/assets/05e7daee-deff-41ef-8651-2af4d1b6aee1)

**Comment by zma69650** [comment]
前面搞错了，是打印的问题setprecision(2)，目前还没找到原因

**Comment by zma69650** [comment]
在仿真中，当计算观察者中的ang_vel时，不使用四元数的话就会出现实机的情况：
```
obs_list.push_back(this->obs.ang_vel * this->params.ang_vel_scale);
```

https://github.com/user-attachments/assets/35d595aa-1cac-4318-83c2-6b70b3801b30

**Comment by fan-ziqi** [comment]
我觉得是因为实机的角速度坐标系和仿真及训练不一样。

QuatRotateInverse函数的第一个参数是机器人角度四元数，第二个参数的坐标系是世界坐标系，函数的输出是第二个参数在机身坐标系下的值。

我认为在isaacgym及gazebo中，角速度的坐标系是世界坐标系，需要使用QuatRotateInverse进行坐标系转换，从而obs中角速度的坐标系为机身坐标系。

而在实机上，如果角速度的坐标系就是机身坐标系，则不需要进行转换。

如果在仿真中不使用QuatRotateInverse进行坐标系转换，则obs中的角速度坐标系就与实机一样了，从而导致与实机相同的问题。

你试一下实机运行的时候不适用QuatRotateInverse进行坐标系转换，看看能不能解决这个问题

**Comment by zma69650** [comment]
你是对的，现在问题解决了，仿真中得加QuatRotateInverse，实机部署则不需要。我整理代码先，然后提交一下Go2的实机部署的代码。

**Comment by fan-ziqi** [comment]
恭喜。这块坐标系的判定我也可能改一下，下周出差回去弄，改好了我在这个issue说一下
---- 回复的原邮件 ----
发件人 JiJie ***@***.***> 日期 2024年10月12日 12:41 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [fan-ziqi/rl_sar] Bug in rl_sar During Real-world Deployment: Controller Crashes on Rotation Over 180 Degrees (Issue #26) 
你是对的，现在问题解决了，仿真中得加QuatRotateInverse，实机部署则不需要。我整理代码先，然后提交一下Go2的实机部署的代码。

**Comment by fan-ziqi** [comment]
#27
