### ISSUE TITLE
No module named 'rl_sdk'

### ISSUE THREAD

**Issue by jingdaliang** [fan-ziqi/rl_sar#28]
![8EF338669ACE22A7BA40173138B7213B](https://github.com/user-attachments/assets/e2da95e6-a120-4296-92b9-db0aa2fce1b6)
哈楼，我这个在这里报错，如何解决，求解答

**Comment by fan-ziqi** [comment]
请根据Issue模板修改您的提问内容

**Comment by fan-ziqi** [comment]
请使用issue模板进行提问
