### ISSUE TITLE
[Bug Report]  No module named "rl-sdk"

### ISSUE THREAD

**Issue by jingdaliang** [fan-ziqi/rl_sar#29]
大佬，我这个在这里报错，是为什么呀，求解答
![8EF338669ACE22A7BA40173138B7213B](https://github.com/user-attachments/assets/6fc5d729-4e1b-47dc-8d22-79e59b666333)

**Comment by fan-ziqi** [comment]
请根据issue模板反馈bug，就一张图我无法为您解答
