### ISSUE TITLE
编译错误，似乎与numpy有关

### ISSUE THREAD

**Issue by Lockedb** [fan-ziqi/rl_sar#36]
### Describe the bug

当我使用catkin build编译时，出现报错，似乎与找不到numpy有关，我查看能找到numpy版本为1.24.4

### Steps to reproduce

catkin build

出现如下图报错

![bug](https://github.com/user-attachments/assets/7c5cd847-5919-409f-a0bc-c812724fa7de)

### System Info

- OS: [Ubuntu 20.04]
- ROS Version: [noetic]
- Python Version: [Python 3.8.10]

### Additional context

无

**Comment by Sivan666666** [comment]
你好，这应该就是numpy版本或者未安装的问题
我的环境numpy version==1.19.5 成功编译
你可以试试换个numpy版本
