### ISSUE TITLE
I want to add unitree robot h1 to this sim, but from unitree repository it lack config/robot_control.yaml.

### ISSUE THREAD

**Issue by Swordros88** [fan-ziqi/rl_sar#8]
robots from https://github.com/unitreerobotics/unitree_ros/tree/master/robots 
Would you show me how to config h1 robot_control.yaml and add config in config.yaml at the same time.

**Comment by fan-ziqi** [comment]
I am currently migrating h1, please check for updates in https://github.com/fan-ziqi/rl_sar/tree/feature-h1-go2
